### ISSUE TITLE
Possíveis Features - Alessandro

### ISSUE THREAD

**Issue by AlessandroMaia** [AceleraDevCSharp/backend#2]
Como podem ver no exemplo que mandei do marcoratti, uma exceção de qualquer aplicação já contém todas as informações que necessitamos, e nossa API só iria receber as informações via JSON ( Afinal, esse é o real funcionamento de uma API, enviar e receber informações), apenas ditaríamos as regras de informações para que ela não retorne um bad request.

![image.png](https://images.zenhubusercontent.com/5edbb45384926806b75b7ee2/c5bdbb5d-447a-474e-811d-f70264d5cf58)

## Passo 1 - tela de login

Simples, com autenticação por login e senha. a autenticação via token será para integrar a API no projeto externo.

![image.png](https://images.zenhubusercontent.com/5edbb45384926806b75b7ee2/96359b93-6e59-4a33-a8de-328824691fdf)

## Passo 2 - tela de cadastro

Segue praticamente igual a tela de login, pois segundo os wireframes da codenation, os dados necessarios para cadastro é Email e senha. Quando o usuário fizer o cadastro, será enviado para o email informado todas as informações e o token gerado. Supondo que a API seja usada em projetos diferentes, no cadastro coloquei um campo para o usuário colocar a identificação do projeto. E teria um combobox com setores pré-cadastrados (desenvolvimento, testes e etc).

![image.png](https://images.zenhubusercontent.com/5edbb45384926806b75b7ee2/d86ddd0f-2bb0-4fcb-ba47-18c15311ff66)

## Passo 3 - tela de esqueci minha senha

Nessa parte, será enviado apenas uma email com senha antiga, caso o email não exista nos cadastros não será enviado nada.

![image.png](https://images.zenhubusercontent.com/5edbb45384926806b75b7ee2/24a35fd1-e35d-4907-8d93-a92291df8c32)

## Passo 4 - tela com a informações da API

Nessa parte irá conter todas as informações, como link de conectar com a API, como é a resposta da mesma quando vem uma requisição GET para ela ou um POST, para agregar ao banco com as informações necessárias.

![image.png](https://images.zenhubusercontent.com/5edbb45384926806b75b7ee2/1b125715-831d-45ca-866a-a1946921afcb)

## 

### CRUD

O CRUD seria sem mistério, apenas na parte de delete, queria colocar um atributo em cada tupla que mostraria que foi "deletada" a informação, porém, este atributo só a deixaria invisível para os filtros de busca.

##

### UML

![image.png](https://images.zenhubusercontent.com/5edbb45384926806b75b7ee2/b56ec9bd-e9c5-4654-b8db-b380d6d36ba1)

# Exemplo

Pegando como exemplo o desafio para entrar no AceleraDev, a requisição GET, como será o retorno na API e para o método POST, o que a nossa API espera.
E também é um exemplo de o que colocar na parte explicativa da pagina da API, como na tela a cima.

![image.png](https://images.zenhubusercontent.com/5edbb45384926806b75b7ee2/3fd50696-0c55-45b2-b248-f9f18db67dc0)

**Comment by bernas1104** [comment]
Sobre o cadastro: separar os usuários por projeto pode ser algo para ser implementado como optativo. Os wireframes não tem nada que indiquem a necessidade de separar usuários por projeto.

Sobre o UML: a tabela "Enviroment" seria o projeto que os usuários fazem parte?

**Comment by gustavovanuncio** [comment]
No UML não teria que ter as chaves primárias das tabelas referenciadas como chave estrangeira nas outras?
Por exemplo: Na USER o usr_id deveria estar referenciado na tabela ERROR_LOG pra identificar qual usuário está tendo o erro.

**Comment by AlessandroMaia** [comment]
Bernardo:
O Enviroment seria os Ambientes de desenvolvimento, a indicação por projeto iria direto no cadastro do usuário.
Tive essa ideia de colocar um campo de projeto, pois nossa API poderia ser feita para projetos diferentes.. No wireframe mostra que nossa API servirá apenas para 1 projeto e minha ideia é poder usá-la em vários.

Gustavo:
Não especifiquei ainda quais serão as chaves estrangeiras, na tabela de USER só coloquei a FK de environment para caso surgisse alguma dúvida do que seria essa tabela. que teria os ambientes pré-cadastro, como ambiente de desenvolvimento, ambiente de testes e etc, pois coloquei que cada Usuario corresponde apenas 1 projeto e 1 ambiente

**Comment by bernas1104** [comment]
Entendi... Eu tinha pensado nisso como uma medida pra evitar redundância, mas tipo... O campo do ambiente só vai armazenar duas informações (id e nome) e o usuário (pode explicar porque é o usuário que interage com o ambiente? Pelos wireframes, o erro é que seria associado com o ambiente, não?) vai possuir a referência. Em questão de armazenamento, a gente vai armazenar mais dados com as duas tabelas do que inserindo o ambiente direto no usuário (ou no erro), do que se usasse o ambiente apenas como uma coluna do usuário (ou erro), percebe isso?

Por exemplo:

Usuário 1
... outras infos
ambiente = dev (essa informação consome x bytes)

vs.

Usuário 2
... outras infos
ambiente_id (consome y bytes)

Ambiente Dev
id (consome z bytes)
nome = dev (consome x bytes)

**Comment by AlessandroMaia** [comment]
Entendi, realmente é uma boa tirar essa tabela de ambiente e colocar direto no usuário. E colocar no combo box, para o usuario apenas selecionar  ambiente, pois evitar escrever errado. tinhamos que pensar assim tambem em relação ao projeto, pois imagina que o projeto X (maiusculo) o usuario escreve x (minusculo), no caso da case da pra arrumar, porém o problema é uma escrita errada. tem que colocar algo no cadastro para padronizar a escrita do nome dos projetos.
